name: 'Publish to NPM'
description: 'Publish an npm package from a package.json'
inputs:
  npm-token: 
    description: "Authentication token to use when publishing to NPM"
    required: true
  npm-tag:
    description: "Tag to attach to the published version, see https://docs.npmjs.com/cli/v8/commands/npm-publish#tag"
    required: false
    default: "latest"
  working-directory:
    description: "Path within the repo to the folder where the package.json file lives"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: write tempoarary project .npmrc
      run: |
        cat >.npmrc <<"END"
        //registry.npmjs.org/:_authToken=${NPM_TOKEN}
        END
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: publish package
      run: |
        npm publish --access public --tag ${{ inputs.npm-tag }}
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Remove temporary .npmrc file
      run: |
        rm .npmrc
      shell: bash
      working-directory: ${{ inputs.working-directory }}
