name: Test

on: 
  push:
    branches:
      - main

jobs:
  test-publish-gem:
    name: It publishes an NPM package in a folder
    runs-on: ubuntu-latest
    environment: Publish to NPM
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set unique package version
        id: set-version
        run: |
          version=0.0.$GITHUB_RUN_NUMBER
          npm version $version
          echo "::set-output name=version::$version"
        working-directory: "javascript"
      - name: Test the action
        uses: ./
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          working-directory: "javascript"
      - name: Assert that latest published package version is as expected
        timeout-minutes: 1
        run: |
          version=0.0.0
          while [[ "$version" != "0.0.${{ github.run_number }}" ]]
          do
            version=$(curl https://registry.npmjs.org/@cucumber/test-release-automation | jq -r '."dist-tags".latest')
          done